# docker-compose.coolify.yml
services:
  frontend:
    build:
      context: .
      dockerfile: apps/application/Dockerfile
      target: production
      args:
        - VITE_CONVEX_URL=${VITE_CONVEX_URL}
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
        - VITE_DOCUMENT_PROCESSOR_URL=${VITE_DOCUMENT_PROCESSOR_URL}
    expose:
      - "80"
    env_file:
      - .env.local
    environment:
      - VITE_DOCUMENT_PROCESSOR_URL=${VITE_DOCUMENT_PROCESSOR_URL}
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
    depends_on:
      document-processor:
        condition: service_healthy
    networks: [stack]

  document-processor:
    build:
      context: .
      dockerfile: apps/document-processor/Dockerfile
    expose:
      - "4001"
    env_file:
      - .env.local
    environment:
      - PORT=4001
      - REDIS_URL=redis://redis:6379
      - WORKER_CONCURRENCY=2
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks: [stack]

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes: [redis_data:/data]
    networks: [stack]

volumes:
  redis_data:

networks:
  stack:
    driver: bridge